# Generated by Django 4.2.11 on 2024-03-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
