# Generated by Django 4.2.11 on 2024-03-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_jokes', '0003_category_alter_joke_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='the_jokes.category'),
        ),
    ]
