# Generated by Django 4.2.11 on 2024-03-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_jokes', '0006_joke_age_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='joke',
            name='labels',
            field=models.ManyToManyField(blank=True, to='the_jokes.label'),
        ),
    ]
