# Generated by Django 4.2.11 on 2024-03-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='joke',
            name='title_number',
        ),
        migrations.AlterField(
            model_name='joke',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
