# Generated by Django 4.2.11 on 2024-03-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0004_alter_joke_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joke',
            options={'ordering': ['?']},
        ),
    ]
