# Generated by Django 4.2.11 on 2024-03-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_remove_comment_status_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='slug',
            field=models.SlugField(default=models.AutoField(primary_key=True, serialize=False), max_length=200, unique=True),
        ),
    ]
