# Generated by Django 4.2.11 on 2024-03-12 13:05

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0009_alter_joke_id_alter_joke_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='slug',
            field=models.SlugField(default=builtins.id),
        ),
    ]
