# Generated by Django 4.2.11 on 2024-03-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0010_alter_joke_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='joke',
            name='slug',
            field=models.SlugField(default=models.AutoField(primary_key=True, serialize=False), unique=True),
        ),
    ]
