# Generated by Django 4.2.11 on 2024-03-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0011_alter_joke_id_alter_joke_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='slug',
        ),
    ]
